### ISSUE TITLE
If I have a dataset with no "time" column ?

### ISSUE THREAD

**Issue by OUALIDBO** [andruekonst/weighted-random-survival-forest#1]
How to make it work with a simple binary dataset without time column ?

**Comment by andruekonst** [comment]
If you have a survival dataset with different column corresponding to the time (like days, months), you can rename it to the "time".
Otherwise you can make an artificial time column based on row number, if data is sorted by time: `dataset["time"] = pd.Series([i for i in range(len(dataset.index))], index=dataset.index)`. In this case make sure, that test data will have correct time scale.
